resume: false
test_only: false
seed: 0
num_workers: 4

benchmark: "ucf101-8at16"

dataset:
  name: "ucf101"
  fold: 1
  batch_size: 28
  clip_duration: 0.5
  video_fps: 16.
  crop_size: 112
  train:
    split: "trainlist{fold:02d}"
    mode: "clip"
    clips_per_video: 5
    use_augmentation: true
    use_shuffle: true
    drop_last: true
  test:
    split: "testlist{fold:02d}"
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    use_shuffle: false
    drop_last: false
  test_dense:
    split: "testlist{fold:02d}"
    mode: "video"
    clips_per_video: 25
    use_augmentation: false
    use_shuffle: false
    drop_last: false

optimizer:
  name: "adam"
  num_epochs: 20
  weight_decay: 0.0
  warmup_classifier: true
  lr:
    name: "multistep"
    base_lr: 0.0001
    gamma: 0.3
    milestones: [8, 12, 16]

model:
  name: "lreg_classifier"
  args:
    n_classes: 101
    feat_name: "pool"
    pooling_op: null
    feat_dim: 512
    use_dropout: true
    dropout: 0.5
