resume: true
num_workers: 8

log2tb: true
seed: 0
distributed: false
print_freq: 100

benchmark: "avc-transf-4crop-yt360"
use_transf: 'audio'
ft_all: false

dataset:
  name: "yt360"
  full_res: false
  fold: 1
  sampling: 'video'   # video, clip
  batch_size: 32
  video_clip_duration: 0.5
  video_fps: 16.
  crop_size: 112
  audio_input: 'ambix'
  audio_clip_duration: 1.
  audio_fps: 24000
  spectrogram_fps: 100.
  n_fft: 512
  n_mels: 128
  augm_per_clip: 4
  use_temporal_augm: false
  use_spatial_augm: true
  crop_method: 'random'
  return_pos: true
  horizon_only: false
  crop_margin: 0.2
  hfov_lims: [0.0707, 0.25]
  train:
    subset: 'train'
    mode: "clip"
    use_augmentation: true
    drop_last: true
    clips_per_video: 1
  test:
    subset: 'test'
    mode: "clip"
    clips_per_video: 1
    use_augmentation: false
    drop_last: false

optimizer:
  name: "adam"
  weight_decay: 0.00001
  num_epochs: 10
  lr:
    name: "multistep"
    base_lr: 0.00001
    gamma: 0.1
    milestones: [5, 8]

model:
  name: "avc_wrapper"
  args:
    use_dropout: true
    dropout: 0.5